# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Jarvis 2.0")
        MainWindow.resize(1440, 900)
        MainWindow.setMinimumSize(800, 600)  # Set minimum window size
        MainWindow.setStyleSheet("QMainWindow {background: #000000;}")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Create main layout
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        
        # Create background container
        self.backgroundContainer = QtWidgets.QWidget(self.centralwidget)
        self.backgroundContainer.setStyleSheet("""
            QWidget {
                background: #000000;
                color: #FFFFFF;
            }
        """)
        
        # Main background with overlay effect
        self.label = QtWidgets.QLabel(self.backgroundContainer)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Jarvis/utils/images/live_wallpaper.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        
        # Add a semi-transparent overlay for better text visibility
        self.overlay = QtWidgets.QLabel(self.centralwidget)
        self.overlay.setGeometry(QtCore.QRect(0, 0, 1440, 900))
        self.overlay.setStyleSheet("background-color: rgba(0, 0, 0, 0.3);")
        
        # Add circular glowing ring effect
        self.ring = QtWidgets.QLabel(self.centralwidget)
        self.ring.setGeometry(QtCore.QRect(620, 300, 200, 200))
        self.ring.setStyleSheet("""
            QLabel {
                background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, 
                    stop:0 rgba(0, 170, 255, 150), 
                    stop:0.8 rgba(0, 170, 255, 30),
                    stop:1 rgba(0, 170, 255, 0));
                border-radius: 100px;
            }
        """)
        # Create input layout at the bottom
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setContentsMargins(20, 10, 20, 20)
        self.inputLayout.setSpacing(10)
        
        # Modern Text Input Field with glow effect
        self.textInput = QtWidgets.QLineEdit(self.centralwidget)
        self.textInput.setMinimumHeight(51)
        self.textInput.setStyleSheet("""
            QLineEdit {
                background-color: rgba(0, 0, 0, 0.7);
                font-family: 'Segoe UI';
                font-size: 14pt;
                color: #FFFFFF;
                border: 2px solid #00AAFF;
                border-radius: 25px;
                padding: 10px 20px;
            }
            QLineEdit:focus {
                border: 2px solid #00FFAA;
                background-color: rgba(0, 170, 255, 0.1);
            }
            QLineEdit::placeholder {
                color: rgba(255, 255, 255, 0.5);
            }
        """)
        self.textInput.setPlaceholderText("✨ Enter your command here...")
        self.textInput.setObjectName("textInput")
        self.inputLayout.addWidget(self.textInput, 3)  # Give text input more space
        
        # Voice Command Button (Blue) with hover effect
        self.pushButton = QtWidgets.QPushButton("🎤", self.centralwidget)
        self.pushButton.setMinimumHeight(51)
        self.pushButton.setStyleSheet("""
            QPushButton {
                background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #0088CC, stop:1 #00AAFF);
                font-family: 'Segoe UI';
                font-size: 16pt;
                font-weight: bold;
                color: white;
                border: none;
                border-radius: 25px;
                padding: 5px;
            }
            QPushButton:hover {
                background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #00AAFF, stop:1 #00CCFF);
                border: 2px solid #33CCFF;
            }
            QPushButton:pressed {
                background-color: #0088CC;
            }
        """)
        self.pushButton.setObjectName("pushButton")
        self.inputLayout.addWidget(self.pushButton, 1)
        
        # Send Text Button (Green) with hover effect
        self.textButton = QtWidgets.QPushButton("⮫", self.centralwidget)
        self.textButton.setMinimumHeight(51)
        self.textButton.setStyleSheet("""
            QPushButton {
                background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #00AA88, stop:1 #00FFAA);
                font-family: 'Segoe UI';
                font-size: 16pt;
                font-weight: bold;
                color: white;
                border: none;
                border-radius: 25px;
                padding: 5px;
            }
            QPushButton:hover {
                background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #00FFAA, stop:1 #00FFCC);
                border: 2px solid #33FFCC;
            }
            QPushButton:pressed {
                background-color: #00AA88;
            }
        """)
        self.textButton.setObjectName("textButton")
        self.inputLayout.addWidget(self.textButton, 1)
        
        # Exit Button (Red) with hover effect
        self.pushButton_2 = QtWidgets.QPushButton("⨉", self.centralwidget)
        self.pushButton_2.setMinimumHeight(51)
        self.pushButton_2.setStyleSheet("""
            QPushButton {
                background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #CC0000, stop:1 #FF0000);
                font-family: 'Segoe UI';
                font-size: 16pt;
                font-weight: bold;
                color: white;
                border: none;
                border-radius: 25px;
                padding: 5px;
            }
            QPushButton:hover {
                background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #FF0000, stop:1 #FF3333);
                border: 2px solid #FF3333;
            }
            QPushButton:pressed {
                background-color: #CC0000;
            }
        """)
        self.inputLayout.addWidget(self.pushButton_2, 1)
        
        # Add input layout to main layout
        self.mainLayout.addStretch(1)  # Push input to bottom
        self.mainLayout.addLayout(self.inputLayout)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 401, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Jarvis/utils/images/initiating.gif"))
        self.label_2.setObjectName("label_2")
        # Create header layout for date and time
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setContentsMargins(20, 20, 20, 0)
        self.headerLayout.setSpacing(20)
        
        # Date display with modern styling
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMaximumHeight(61)
        self.textBrowser.setStyleSheet("""
            QTextBrowser {
                font-family: 'Segoe UI';
                font-size: 18pt;
                font-weight: bold;
                background-color: rgba(0, 170, 255, 0.1);
                color: #00AAFF;
                border: 2px solid rgba(0, 170, 255, 0.5);
                border-radius: 15px;
                padding: 10px;
            }
        """)
        self.textBrowser.setObjectName("textBrowser")
        self.headerLayout.addWidget(self.textBrowser, 1)
        
        # Time display with modern styling
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setMaximumHeight(61)
        self.textBrowser_2.setStyleSheet("""
            QTextBrowser {
                font-family: 'Segoe UI';
                font-size: 18pt;
                font-weight: bold;
                background-color: rgba(0, 255, 170, 0.1);
                color: #00FFAA;
                border: 2px solid rgba(0, 255, 170, 0.5);
                border-radius: 15px;
                padding: 10px;
            }
        """)
        self.headerLayout.addWidget(self.textBrowser_2, 1)
        
        # Add header layout to main layout
        self.mainLayout.addLayout(self.headerLayout)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(1000, 500, 431, 281))
        self.textBrowser_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\ncolor:white;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        # Add status text display
        self.statusText = QtWidgets.QLabel(self.centralwidget)
        self.statusText.setStyleSheet("""
            QLabel {
                color: #00FFAA;
                font-family: 'Segoe UI';
                font-size: 14pt;
                padding: 10px;
            }
        """)
        self.statusText.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLayout.addWidget(self.statusText)
        
        # Set up central widget
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Remove menu and status bars for cleaner look
        MainWindow.setMenuBar(None)
        MainWindow.setStatusBar(None)
        
        # Make sure the background image fills the window
        MainWindow.resizeEvent = lambda event: self.label.setGeometry(
            0, 0, event.size().width(), event.size().height())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JARVIS 2.0"))
        self.pushButton.setText(_translate("MainWindow", "Voice"))
        self.textButton.setText(_translate("MainWindow", "Send"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
